version: 3.9

networks:
 mana-net:
 external: true

services:
 reverse-proxy:
 image: nginx:alpine
 container_name: reverse-proxy
 restart: unless-stopped
 ports:
 - 80:80
 - 443:443
 volumes:
 - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
 - /etc/letsencrypt/live/manaproject.app/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
 - /etc/letsencrypt/live/manaproject.app/privkey.pem:/etc/nginx/certs/privkey.pem:ro
 - ./nginx/acme:/var/www/acme:ro
 networks:
 - mana-net
 healthcheck:
 test: [CMD,wget,-qO-,http://localhost/health]
 interval: 15s
 timeout: 5s
 retries: 3
